FROM node:22-alpine

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY . .

EXPOSE 4200

CMD ["pnpm", "start", "--", "--host", "0.0.0.0", "--poll", "2000"]
