version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sigba_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: sigba_mailpit
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data: